### PR TITLE
Create stack and add publication to stack

### PR DESCRIPTION
**Pull request by Marie000**
This covers creating a tag and assigning a tag to a publication. 

To create a tag, we need to post an activity:
```
@context: ....
type: 'Create',
object: { type: 'reader:Stack', name: 'mystack' }
```

To assign a tag to a publication, we need to post an activity:
```
{
  @context: ....,
  type: 'Add'
  object: tagObject
  target: publicationObject
}
```
(this returns a 200 response, but I guess we could also make it a 201 response)

@baldurbjarnason let me know if that works for you. 
another option might be to pass in only the tag id (url) and publication id. I think that would work also, but I'd have to check.

### CODE REVIEW

**Comment by Marie000** [comment]
also connected to issue #109

**Comment by Marie000** [comment]
One thing that worries me with my current implementation is that the type of tag is stored in the database in the json field. Right now we only have one type ('reader:Stack') but in the future we might have other types and if we ever need to handle requests for one particular type, it would make sense to do that at the database level.

**Comment by Marie000** [comment]
also, currently the database does not do anything to prevent having the same tag assigned to the same publication more than once.

**Comment by baldurbjarnason** [comment]
Yeah, I hear your worries about the DB structure. It makes sense to surface the tag type to be a proper DB field, long term.

Not preventing multiple identical tags on the same publication might be a bit of an issue. Or it might not. 🙂 It's something to bear in mind on the front end work and see how it goes.

**Comment by Marie000** [comment]
I will create issues for future improvements.
But what bothers me about having the type in the json is that I have no idea how it ends up there. :confused: 

But I will merge this (as soon as I finish fixing the flow types) so we have this working.

**Pull request merged**
