### PR TITLE
Refactor README, introduce development guide

### PR DESCRIPTION
**Pull request by nicholasjhenry**
This is the first PR in a series to improve documentation and the onboarding experience for new developers.

* Simplifies the `README.md` to provide an overview of the project without overwhelming the reader.
* Adds a development guide to get new developers set up (based on my experience of setting up the project).
* Adds an overview guide extracted from the `README.md`. 

No information was lost from the original README in this documentation revision, just extracted to other files and reformatted.

NOTE: the development guide does not cover running the server locally to develop with `ink-library`. This will come later in another PR. This only gets a successful test environment running.

### CODE REVIEW

**Comment by nicholasjhenry** [comment]
@Marie000 Do think you will have time to look at this today, please?

**Review by Marie000 — CHANGES_REQUESTED** [review]
We can remove all the mentions of ActivityPub and the whole activity.md file. The rest is good.

**Comment by nicholasjhenry** [comment]
@Marie000 Is this good to merge?

**Comment by nicholasjhenry** [comment]
@Marie000 any update on this?

**Pull request merged**
