### PR TITLE
trying to encrypt google file for travis

### PR DESCRIPTION
**Pull request by Marie000**

### CODE REVIEW

**Comment by Marie000** [comment]
makes sense. We can set up automatic deploys when (and if) we need it.
The encrypted google setup file wasn't working anyways. Travis doesn't allow the use of encrypted files for pull requests from a fork.

**Comment by baldurbjarnason** [comment]
Yeah. The pull request issue was something we encountered before you joined the team. Was very annoying then and is very annoying now.

Test pass; looks good 🙂 👍 🎉  

(Also, when the time comes [GitHub Actions](https://github.com/features/actions) might by then have become an easier to use path to deployment letting us keep deployment and integration testing somewhat separate.)

**Comment by Marie000** [comment]
:tada: :smiley: 

Right now it is running only the unit tests. With my other pull request I changed the npm test script to run all tests (and npm run test-unit to run only unit tests). I wish I could run that through Travis, but it doesn't see that pull request because it predates the switch to public. If that breaks everything, I can always fix in another PR.

**Comment by Marie000** [comment]
actually, I might divide the tests into stages. That will make it clearer in the pull request which set of tests is failing.

**Pull request merged**
